### ISSUE TITLE
Use GPS for position tracking

### ISSUE THREAD

**Issue by MDaniel96** [MDaniel96/paintball-admin-app#14]
- [x] Add new 2 GPS coordinate properties to map models
- [x] Store a GPS game with map and players in H2, make it work in the game
- [x] Add a GPS coordinates polling service, use it in Map activity
- [x] Add a new position calculator which calculates player's location (in mm on map) based on gps coordinates
- [x] Convert mm to pixels (with the given GPS coordinates) and display players location
- [x] Send it through MQTT and test it
